version: '3.1'

services:
  php:
    depends_on:
      - db
    image: docker-php-dev
    restart: always
    ports:
      - 5000:80
    volumes:
      - ./development:/var/www/html

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PMA_HOST: db

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

volumes:
  wordpress_db:
  wordpress_uploads:
